# Hyprpaper wallpaper configurations

# Load wallpapers
preload = ~/Pictures/Wallpapers/cyberpunk_2077_6.jpeg

# Set wallpapers
wallpaper = DP-2,~/Pictures/Wallpapers/cyberpunk_2077_6.jpeg
wallpaper = DP-5,~/Pictures/Wallpapers/cyberpunk_2077_6.jpeg
wallpaper = DP-1,~/Pictures/Wallpapers/cyberpunk_2077_6.jpeg
wallpaper = DP-4,~/Pictures/Wallpapers/cyberpunk_2077_6.jpeg

# Misc settings
splash = false
