# Hyprpaper wallpaper configurations

# Load wallpapers
preload = ~/Pictures/honda_nsx.png

# Set wallpapers
wallpaper = DP-2,~/Pictures/honda_nsx.png
wallpaper = DP-5,~/Pictures/honda_nsx.png
wallpaper = DP-1,~/Pictures/honda_nsx.png
wallpaper = DP-4,~/Pictures/honda_nsx.png

# Misc settings
splash = false
